# Generated by Django 3.1.3 on 2020-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201120_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/bert.gif', upload_to='images/'),
            preserve_default=False,
        ),
    ]
