# Generated by Django 3.2.6 on 2021-08-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('draw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('awayTeam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='awayTeam', to='app_nfl.team')),
                ('homeTeam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='homeTeam', to='app_nfl.team')),
            ],
        ),
    ]
