# Generated by Django 3.2.6 on 2021-08-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nfl', '0002_auto_20210811_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
