# Generated by Django 3.2.6 on 2021-08-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nfl', '0003_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
    ]
