# Generated by Django 3.2.6 on 2021-08-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('cohort', models.CharField(max_length=6)),
                ('favorite_topic', models.CharField(max_length=120)),
                ('favorite_teacher', models.CharField(max_length=120)),
                ('capstone_url', models.CharField(max_length=70)),
            ],
        ),
    ]
