# Generated by Django 3.2.5 on 2021-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
