# Generated by Django 3.2.5 on 2021-07-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocerylist', '0002_auto_20210723_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
