# Generated by Django 3.2.5 on 2021-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocerylist', '0003_alter_item_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
