# Generated by Django 3.2.5 on 2021-07-26 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='code_for_url',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='submittedurl',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 20, 54, 50, 542767, tzinfo=utc)),
        ),
    ]
