# Generated by Django 3.2.5 on 2021-07-26 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_auto_20210726_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 11, 33, 895140, tzinfo=utc)),
        ),
    ]
