# Generated by Django 3.2.6 on 2021-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
