# Generated by Django 3.2.6 on 2021-08-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_tags',
            field=models.ImageField(blank=True, null=True, upload_to='type_tags/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='animated/'),
        ),
    ]
