# Generated by Django 3.2.6 on 2021-08-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20210809_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type_tags',
            new_name='type_tag',
        ),
    ]
