# Generated by Django 3.2.6 on 2021-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_rename_type_tags_type_type_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='cry',
            field=models.FileField(blank=True, null=True, upload_to='cries/'),
        ),
    ]
