# Generated by Django 3.2.6 on 2021-09-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_pokemon_cry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='sound_effects/')),
            ],
        ),
    ]
