# Generated by Django 3.2.5 on 2021-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=200)),
                ('fav_topic', models.CharField(max_length=200)),
                ('fav_teacher', models.CharField(max_length=200)),
                ('capstone', models.URLField()),
            ],
        ),
    ]
