# Generated by Django 3.2.5 on 2021-07-27 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20210723_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 19, 11, 30, 211432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
