# Generated by Django 3.2.5 on 2021-07-27 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_auto_20210727_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 20, 35, 13, 58051, tzinfo=utc)),
        ),
    ]
