# Generated by Django 3.2.5 on 2021-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
