# Generated by Django 3.2.5 on 2021-07-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='created',
        ),
        migrations.RemoveField(
            model_name='shortener',
            name='times_followed',
        ),
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, default='anything', max_length=15, unique=True),
        ),
    ]
