# Generated by Django 3.2.7 on 2021-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_caught_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pokemon_caught',
            field=models.ManyToManyField(related_name='caught_by_user', to='pokemon.Pokemon'),
        ),
    ]
