# Generated by Django 3.2.6 on 2021-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=16)),
                ('lastname', models.CharField(max_length=16)),
                ('cohort', models.CharField(max_length=16)),
                ('favorite_topic', models.CharField(max_length=16)),
                ('favorite_teacher', models.CharField(max_length=16)),
                ('capstone', models.URLField(max_length=16)),
            ],
        ),
    ]
