# Generated by Django 3.2.6 on 2021-08-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='capstone',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='favorite_teacher',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='favorite_topic',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
