# Generated by Django 3.2.7 on 2021-09-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
