# Generated by Django 3.2.7 on 2021-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_auto_20210906_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
