# Generated by Django 3.2.5 on 2021-07-23 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 7, 23, 19, 20, 46, 578426, tzinfo=utc))),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('done_box', models.BooleanField(verbose_name="CHECK HERE when you've bought the item!")),
            ],
        ),
    ]
