# Generated by Django 3.2.5 on 2021-07-22 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 7, 22, 22, 18, 11, 233129, tzinfo=utc))),
                ('completed_date', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
