# Generated by Django 3.2.5 on 2021-07-22 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 22, 20, 37, 879558, tzinfo=utc)),
        ),
    ]
