# Generated by Django 3.2.5 on 2021-07-23 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20210722_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 17, 52, 41, 257802, tzinfo=utc)),
        ),
    ]
