# Generated by Django 3.2.5 on 2021-07-23 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_alter_groceryitem_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 17, 54, 8, 267126, tzinfo=utc)),
        ),
    ]
