# Generated by Django 3.2.7 on 2021-09-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='caught_by',
        ),
    ]
