# Generated by Django 3.2.7 on 2021-09-10 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0002_remove_pokemon_caught_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='caught_by',
            field=models.ManyToManyField(related_name='caught', to=settings.AUTH_USER_MODEL),
        ),
    ]
