# Generated by Django 3.2.5 on 2021-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField()),
                ('purchased', models.BooleanField()),
            ],
        ),
    ]
