# Generated by Django 2.1.3 on 2018-11-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vg_chars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='develop',
            new_name='developer',
        ),
    ]
