# Generated by Django 3.2.5 on 2021-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='body',
            field=models.TextField(max_length=128),
        ),
    ]
