# Generated by Django 3.1.3 on 2020-11-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201119_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='caption',
        ),
    ]
