# Generated by Django 2.1.2 on 2018-10-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('long_url', models.CharField(max_length=2000)),
                ('code', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
