# Generated by Django 2.1.2 on 2018-10-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('http_referer', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='click',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.URL'),
        ),
    ]
