# Generated by Django 3.2 on 2021-08-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_caught_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pokemon_caught',
            field=models.ManyToManyField(related_name='caught_by_users', to='pokemon.Pokemon'),
        ),
    ]
