# Generated by Django 3.2.5 on 2021-07-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('url_name', models.CharField(max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('click_date', models.DateTimeField(auto_now_add=True)),
                ('related_url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='url_shortener.urlshortener')),
            ],
        ),
    ]
