# Generated by Django 3.2.5 on 2021-07-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_urlshortener_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickdata',
            name='clicks_to_date',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
