


import requests

from currency_exchange_secrets import currency_exchange_api_key

# import currency_exchange_secrets
# currency_exchange_secrets.currency_exchange_api_key

countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Banglades',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian O. Terr.',
    'British Virgin Islands',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Cayman Islands',
    'Central African Rep.',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos ',
    'Colombia',
    'Comoros',
    'Congo ',
    'Cook Islands',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of Congo ',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'European Union',
    'Falkland Isl.',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Terr.',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Great Britain ',
    'Greece',
    'Greenland ',
    'Grenada',
    'Guadaloupe',
    'Guam ',
    'Guatemala',
    'Guernsey',
    'Guinea ',
    'Guinea Bissau',
    'Guyana',
    'Haiti',
    'Heard and McDonald Isl.',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyz Republic',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherland Antilles',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'North Korea',
    'Northern Mariana Isl.',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Reunion',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Saint Lucia',
    'Saint Pierre and Miquelon',
    'San Marino',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten ',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and South Sandwich Islands',
    'South Korea',
    'South Sudan',
    'Soviet Union',
    'Spain',
    'Sri Lanka',
    'St. Helena',
    'St. Tome and Principe',
    'St.Kitts Nevis Anguilla',
    'St.Vincent and Grenadines',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen Is',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United States',
    'Uruguay',
    'US Minor outlying Isl.',
    'US Virgin Islands',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City State',
    'Venezuela',
    'Vietnam',
    'Wallis and Futuna Islands',
    'Western Sahara',
    'Western Samoa',
    'Yemen',
    'Yugoslavia',
    'Zambia',
    'Zimbabwe'
]



currencies = [
    'AFN',
    'ALL',
    'DZD',
    'USD',
    'EUR',
    'AOA',
    'XCD',
    'XCD',
    'ARS',
    'AMD',
    'AWG',
    'AUD',
    'EUR',
    'AZN',
    'BSD',
    'BHD',
    'BDT',
    'BBD',
    'BYN',
    'EUR',
    'BZD',
    'XOF',
    'BMD',
    'BTN',
    'BOB',
    'BAM',
    'BWP',
    'NOK',
    'BRL',
    'GBP',
    'USD',
    'BND',
    'BGN',
    'XOF',
    'BIF',
    'KHR',
    'XAF',
    'CAD',
    'CVE',
    'KYD',
    'XAF',
    'XAF',
    'CLP',
    'CNY',
    'AUD',
    'AUD',
    'COP',
    'KMF',
    'XAF',
    'NZD',
    'CRC',
    'HRK',
    'CUC',
    'EUR',
    'CZK',
    'CDF',
    'DKK',
    'DJF',
    'XCD',
    'DOP',
    'USD',
    'EGP',
    'SVC',
    'ERN',
    'EUR',
    'ETB',
    'EUR',
    'FKP',
    'DKK',
    'FJD',
    'EUR',
    'EUR',
    'EUR',
    'EUR',
    'XPF',
    'EUR',
    'XAF',
    'GMD',
    'GEL',
    'EUR',
    'GHS',
    'GIP',
    'GBP',
    'EUR',
    'DKK',
    'XCD',
    'EUR',
    'USD',
    'GTQ',
    'GGP',
    'GNF',
    'XAF',
    'GYD',
    'HTG',
    'AUD',
    'HNL',
    'HKD',
    'HUF',
    'ISK',
    'INR',
    'IDR',
    'IRR',
    'IQD',
    'EUR',
    'IMP',
    'ILS',
    'EUR',
    'XOF',
    'JMD',
    'JPY',
    'JEP',
    'JOD',
    'KZT',
    'KES',
    'KID',
    'KWD',
    'KGS',
    'LAK',
    'EUR',
    'LBP',
    'LSL',
    'LRD',
    'LYD',
    'CHF',
    'LTL',
    'EUR',
    'MOP',
    'MKD',
    'MGA',
    'MWK',
    'MYR',
    'MVR',
    'XOF',
    'EUR',
    'USD',
    'EUR',
    'MRU',
    'MUR',
    'EUR',
    'MXN',
    'USD',
    'MDL',
    'EUR',
    'MNT',
    'EUR',
    'XCD',
    'MAD',
    'MZN',
    'MMK',
    'NAD',
    'AUD',
    'NPR',
    'ANG',
    'EUR',
    'XPF',
    'NZD',
    'NIO',
    'XOF',
    'NGN',
    'NZD',
    'AUD',
    'KPW',
    'USD',
    'NOK',
    'OMR',
    'PKR',
    'USD',
    'ILS',
    'PAB',
    'PGK',
    'PYG',
    'PEN',
    'PHP',
    'NZD',
    'PLN',
    'EUR',
    'USD',
    'QAR',
    'EUR',
    'RON',
    'RUB',
    'RWF',
    'XCD',
    'EUR',
    'EUR',
    'SAR',
    'XOF',
    'RSD',
    'SCR',
    'SLL',
    'SGD',
    'ANG',
    'EUR',
    'EUR',
    'SBD',
    'SOS',
    'ZAR',
    'GBP',
    'KRW',
    'SSP',
    'RUB',
    'EUR',
    'LKR',
    'SHP',
    'STN',
    'XCD',
    'XCD',
    'SDG',
    'SRD',
    'NOK',
    'SZL',
    'SEK',
    'CHF',
    'SYP',
    'TWD',
    'TJS',
    'TZS',
    'THB',
    'USD',
    'XOF',
    'NZD',
    'TOP',
    'TTD',
    'TND',
    'TRY',
    'TMT',
    'USD',
    'AUD',
    'UGX',
    'UAH',
    'AED',
    'USD',
    'UYU',
    'USD',
    'USD',
    'UZS',
    'VUV',
    'EUR',
    'VES',
    'VND',
    'XPF',
    'MAD',
    'WST',
    'YER',
    'YUN',
    'ZMW',
    'ZWL'
]


# [
#     {
#         'country': 'United States',
#         'currency': 'USD'
#     },
#     {
#         'country': 'Thailand',
#         'currency': 'THB'
#     }
# ]


# {
#     'USD': 'United States',
#     'THB': 'Thailand',
# }

# {
#     'United States': 'USD',
#     'Thailand': 'THB',
# }

exchange_rate = {}
for i in range(len(countries)):
    exchange_rate[countries[i]] = currencies[i]
# print(exchange_rate)




# Welcome to the Euro Currency Exchange 5000(tm)
# What country are you converting your currency into? United States
# United States -> USD
# What is the amount? 10
# 10 EUR = 12.09 USD


def get_currency_from_user(text):
    while True:
        # prompt the user for the country they're converting into
        country_name = input(text)
        country_name = country_name.title()
        # look up the currency name using the country
        currency_name = exchange_rate.get(country_name)
        if currency_name is not None:
            break
        print('Could not find that country.')
    return currency_name


def get_exchange_rates():
    # look up the current exchange rate using the api
    # http://api.exchangeratesapi.io/v1/latest?access_key=fk2nfwoef2ijijf2jnf

    url = 'http://api.exchangeratesapi.io/v1/latest'
    response = requests.get(url, params={'access_key': currency_exchange_api_key})
    response = response.json()
    # print(response)

    # look up the exchange rate using the currency name

    response = response['rates']
    return response



currency_from = get_currency_from_user('What country\'s currency would you like to convert from? ')

currency_to = get_currency_from_user('What country\'s currency would you like to convert to? ')

amount_from = float(input('How much currency would you like to convert (EUR)? '))

exchange_rates = get_exchange_rates()

amount_euros = amount_from/exchange_rates[currency_from]
amount_to = amount_euros*exchange_rates[currency_to]

print(f'{amount_from} {currency_from} = {amount_to} {currency_to}')