# Generated by Django 3.2.6 on 2021-08-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_auto_20210727_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(),
        ),
    ]
