# Generated by Django 3.2.5 on 2021-07-22 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_list_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 22, 19, 6, 745513, tzinfo=utc)),
        ),
    ]
